-- Create all the entities

CREATE TABLE contactInfo (
    contactID           NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email               VARCHAR(100)    NOT NULL,
    phone               NUMBER(11)      CHECK(phone BETWEEN 2000000000 AND 9999999999),
    addressLine1        VARCHAR(50)     NOT NULL,
    addressLine2        VARCHAR(50),
    city                VARCHAR(50)     NOT NULL,
    province            VARCHAR(50)     NOT NULL,
    postalCode          VARCHAR(7)      NOT NULL,
    country             VARCHAR(50)     NOT NULL,
    contactFirstName    VARCHAR(50)     NOT NULL,
    contactLastName     VARCHAR(50)     NOT NULL,
    companyName         VARCHAR(50)     NOT NULL
);

CREATE TABLE owners (
    ownerID             NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    contactID           NUMBER(5)       NOT NULL,
    CONSTRAINT owners_contactInfo_fk FOREIGN KEY(contactID) REFERENCES contactInfo(contactID)
);

CREATE TABLE renters (
    renterID            NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    contactID           NUMBER(5)       NOT NULL,
    creditLimit         NUMBER(10,2),
    CONSTRAINT renters_contactInfo_fk FOREIGN KEY(contactID) REFERENCES contactInfo(contactID)
);

CREATE TABLE venues (
    venueID             NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    venueName           VARCHAR(50)     NOT NULL,
    webPage             VARCHAR(100),
    venueDescription    VARCHAR(500),
    ownerID             NUMBER(5)       NOT NULL,
    CONSTRAINT venues_owners_fk FOREIGN KEY(ownerID) REFERENCES owners(ownerID)
);

CREATE TABLE facilities (
    facilityID          NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY,
    venueID             NUMBER(5),
    openTime            NUMBER(5)       NOT NULL CHECK(openTime BETWEEN 1 and 1440),
    closeTime           NUMBER(5)       NOT NULL CHECK(closeTime BETWEEN 1 and 1440),
    square              NUMBER(5),
    childFriendly       NUMBER(1)       NOT NULL,
    capacity            NUMBER(6)       NOT NULL,
    CONSTRAINT facilityID_venueID_pk PRIMARY KEY(facilityID, venueID),
    CONSTRAINT facilities_venues_fk FOREIGN KEY(venueID) REFERENCES venues(venueID)
);

CREATE TABLE reviews (
    reviewID            NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    venueID             NUMBER(5)       NOT NULL,
    renterID            NUMBER(5)       NOT NULL,
    rates               NUMBER(3)       NOT NULL,
    reviewText          VARCHAR(253),
    reviewDate          DATE            NOT NULL,
    CONSTRAINT reviews_venues_fk FOREIGN KEY(venueID) REFERENCES venues(venueID),
    CONSTRAINT reviews_renters_fk FOREIGN KEY(renterID) REFERENCES renters(renterID)
);

CREATE TABLE bookings (
    bookingID           NUMBER(5)       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    renterID            NUMBER(5)       NOT NULL,
    status              VARCHAR(25)     NOT NULL,
    payment             NUMBER(10,2)    DEFAULT(0) NOT NULL,
    confirmationCode    VARCHAR(100)    NOT NULL,
    discountPercent     NUMBER(3)       CHECK(discountPercent BETWEEN 0 AND 100),
    CONSTRAINT bookings_renters_fk FOREIGN KEY(renterID) REFERENCES renters(renterID)
);

CREATE TABLE schedules (
    venueID             NUMBER(5),
    bookingID           NUMBER(5),
    scheduleDate        DATE            NOT NULL,
    fromTime            NUMBER(5)       NOT NULL CHECK(fromTime BETWEEN 1 and 1440),
    toTime              NUMBER(5)       NOT NULL CHECK(toTime BETWEEN 1 and 1440),
    CONSTRAINT venueID_bookingID_pk PRIMARY KEY(venueID, bookingID),
    CONSTRAINT schedules_venues_fk FOREIGN KEY(venueID) REFERENCES venues(venueID),
    CONSTRAINT schedules_bookings_fk FOREIGN KEY(bookingID) REFERENCES bookings(bookingID)
);


--    DROP TABLE schedules;
--    DROP TABLE bookings;
--    DROP TABLE reviews;
--    DROP TABLE facilities;
--    DROP TABLE venues;
--    DROP TABLE renters;
--    DROP TABLE owners;
--    DROP TABLE contactInfo;


-- Insert data into contactInfo table

INSERT ALL
    INTO contactInfo VALUES (1001, 'john.doe@gmail.com', 2234567890, '123 Main Street', 'Apt 1', 'Toronto', 'ON', 'M5V 1B6', 'Canada', 'John', 'Doe', 'Maple Leaf Enterprises')
    INTO contactInfo VALUES (1002, 'info@outlook.com', 5555555555, '789 Broadway', NULL, 'Vancouver', 'BC', 'V6B 1N3', 'Canada', 'Bob', 'Johnson', 'Pacific Coasts Inc')
    INTO contactInfo VALUES (1003, 'mary.smith@yahoo.com', 2112223333, '10 Oak Street', NULL, 'Montreal', 'QC', 'H2Z 1L8', 'Canada', 'Mary', 'Lee', 'Northern Lights Ltd')
    INTO contactInfo VALUES (1004, 'sam.brown@hotmail.com', 9998887777, '15 Elm Ave', 'Suite 3B', 'Calgary', 'AB', 'T2P 1J9', 'Canada', 'Sam', 'Brown', 'Rocky Mountain Services')
    INTO contactInfo VALUES (1005, 'alice.davis@gmail.com', 4443332222, '20 Pine Road', NULL, 'Ottawa', 'ON', 'K1P 5G4', 'Canada', 'Alice', 'Davis', 'Capital Innovations')
    INTO contactInfo VALUES (1006, 'mark.wilson@yahoo.com', 7776665555, '25 Maple Street', NULL, 'Edmonton', 'AB', 'T5J 0N7', 'Canada', 'Mark', 'Wilson', 'Prairie Ventures')
    INTO contactInfo VALUES (1007, 'emily.miller@gmail.com', 2225558888, '30 Oak Ave', 'Apt 2', 'Winnipeg', 'MB', 'R3B 0P4', 'Canada', 'Emily', 'Miller', 'Heartland Holdings')
    INTO contactInfo VALUES (1008, 'david.martinez@outlook.com', 6669991111, '35 Pine Road', NULL, 'Halifax', 'NS', 'B3J 3P7', 'Canada', 'David', 'Martinez', 'Maritime Traders')
    INTO contactInfo VALUES (1009, 'lisa.garcia@yahoo.com', 2114447777, '40 Elm Street', 'Suite 5C', 'Quebec City', 'QC', 'G1K 9H6', 'Canada', 'Lisa', 'Garcia', 'Chateau Industries')
    INTO contactInfo VALUES (1010, 'peter.hernandez@gmail.com', 5557778888, '45 Oak Ave', NULL, 'Victoria', 'BC', 'V8W 1A1', 'Canada', 'Peter', 'Hernandez', 'Pacific Shores Corp')
    INTO contactInfo VALUES (1011, 'susan.ramirez@outlook.com', 9992221111, '50 Pine Road', 'Suite 7A', 'Regina', 'SK', 'S4P 3C7', 'Canada', 'Susan', 'Ramirez', 'Prairie Harvest Co')
    INTO contactInfo VALUES (1012, 'alex.lopez@yahoo.com', 2226669999, '55 Elm Street', NULL, 'St. John''s', 'NL', 'A1C 5M2', 'Canada', 'Alex', 'Lopez', 'Atlantic Exports')
    INTO contactInfo VALUES (1013, 'kate.gomez@gmail.com', 7771114444, '60 Oak Ave', 'Apt 10', 'Charlottetown', 'PE', 'C1A 4B1', 'Canada', 'Kate', 'Gomez', 'Maritime Treasures')
    INTO contactInfo VALUES (1014, 'mike.reed@yahoo.com', 3336669999, '65 Pine Road', NULL, 'Yellowknife', 'NT', 'X1A 2P7', 'Canada', 'Mike', 'Reed', 'Northern Essentials')
    INTO contactInfo VALUES (1015, 'olivia.phillips@gmail.com', 8885552222, '70 Elm Street', 'Suite 12B', 'Whitehorse', 'YT', 'Y1A 2C6', 'Canada', 'Olivia', 'Phillips', 'Yukon Ventures')
    INTO contactInfo VALUES (1016, 'matt.cook@outlook.com', 4447770000, '75 Oak Ave', NULL, 'Iqaluit', 'NU', 'X0A 0H0', 'Canada', 'Matt', 'Cook', 'Arctic Fresh Foods')
    INTO contactInfo VALUES (1017, 'sophia.morgan@yahoo.com', 7770001111, '80 Pine Road', NULL, 'Fredericton', 'NB', 'E3B 1C9', 'Canada', 'Sophia', 'Morgan', 'Maritime Crafts')
    INTO contactInfo VALUES (1018, 'chris.baker@gmail.com', 2223334444, '85 Elm Street', NULL, 'Edmundston', 'NB', 'E3V 1T1', 'Canada', 'Chris', 'Baker', 'St. Lawrence Trading')
    INTO contactInfo VALUES (1019, 'linda.ross@outlook.com', 9993336666, '90 Oak Ave', 'Apt 15', 'Swift Current', 'SK', 'S9H 3X6', 'Canada', 'Linda', 'Ross', 'Prairie Creations')
    INTO contactInfo VALUES (1020, 'james.miller@yahoo.com', 2223334444, '95 Elm Street', NULL, 'Fredericton', 'NB', 'E3B 1G5', 'Canada', 'James', 'Miller', 'Riverbend Invest')
    SELECT * FROM dual;

COMMIT;

-- Insert data into renters table

INSERT ALL
    INTO renters VALUES (1101, 1001, 5000.00)
    INTO renters VALUES (1102, 1002, 10000.00)
    INTO renters VALUES (1103, 1003, 8000.00)
    INTO renters VALUES (1104, 1004, 6000.00)
    INTO renters VALUES (1105, 1005, 7000.00)
    INTO renters VALUES (1106, 1006, 9000.00)
    INTO renters VALUES (1107, 1007, 5500.00)
    INTO renters VALUES (1108, 1008, 7500.00)
    INTO renters VALUES (1109, 1009, 6500.00)
    INTO renters VALUES (1110, 1010, 8500.00)
    SELECT * FROM dual;

COMMIT;

-- Insert data into owners table

INSERT ALL 
    INTO owners VALUES (1111, 1011)
    INTO owners VALUES (1112, 1012)
    INTO owners VALUES (1113, 1013)
    INTO owners VALUES (1114, 1014)
    INTO owners VALUES (1115, 1015)
    INTO owners VALUES (1116, 1016)
    INTO owners VALUES (1117, 1017)
    INTO owners VALUES (1118, 1018)
    INTO owners VALUES (1119, 1019)
    INTO owners VALUES (1120, 1020)
    SELECT * FROM dual;

COMMIT;

-- Insert data into venues table

INSERT ALL
    INTO venues VALUES (2001, 'Venue A', 'https://venuea.com', 'A spacious and modern event space.', 1111)
    INTO venues VALUES (2002, 'Venue B', 'https://venueb.com', 'Elegant ballroom for weddings and parties.', 1111)
    INTO venues VALUES (2003, 'Conference Center X', 'https://conferencecenterx.com', 'State-of-the-art conference facilities.', 1112)
    INTO venues VALUES (2004, 'Garden Oasis', 'https://gardenoasis.com', 'Beautiful garden venue for outdoor events.', 1113)
    INTO venues VALUES (2005,'Rooftop Lounge', 'https://rooftoplounge.com', 'Stunning rooftop venue with city views.', 1114)
    INTO venues VALUES (2006,'The Grand Hall', 'https://thegrandhall.com', 'Historic building perfect for grand celebrations.', 1114)
    INTO venues VALUES (2007,'Club Nights', 'https://clubnights.com', 'Popular nightclub with a vibrant atmosphere.', 1114)
    INTO venues VALUES (2008,'Lakeside Retreat', 'https://lakesideretreat.com', 'Relaxing lakeside venue for corporate retreats.', 1115)
    INTO venues VALUES (2009,'Mountain Lodge', 'https://mountainlodge.com', 'Cozy lodge for mountain getaways.', 1115)
    INTO venues VALUES (2010,'Garden Terrace', 'https://gardenterrace.com', 'Charming terrace garden for outdoor events.', 1115)
    INTO venues VALUES (2011,'The Ballpark', 'https://theballpark.com', 'Sports venue for games and tournaments.', 1116)
    INTO venues VALUES (2012,'Art Gallery X', 'https://artgalleryx.com', 'Gallery space for art exhibitions and events.', 1119)
    INTO venues VALUES (2013,'The Barn', 'https://thebarnvenue.com', 'Rustic barn venue for weddings and parties.', 1119)
    INTO venues VALUES (2014,'Cinema Nights', 'https://cinemanights.com', 'Movie theater venue for private screenings.', 1119)
    INTO venues VALUES (2015,'Tropical Paradise', 'https://tropicalparadise.com', 'Tropical-themed venue for themed parties.', 1120)
    SELECT * FROM dual;

COMMIT;

-- Insert data into facilities table

INSERT ALL
    INTO facilities VALUES (2101, 2001, 8, 23, 1000, 1, 500)
    INTO facilities VALUES (2102, 2001, 12, 22, 800, 0, 300)
    INTO facilities VALUES (2103, 2002, 9, 2, 1200, 0, 400)
    INTO facilities VALUES (2104, 2004, 10, 21, 600, 1, 200)
    INTO facilities VALUES (2105, 2005, 18, 2, 500, 0, 150)
    INTO facilities VALUES (2106, 2006, 14, 22, 900, 0, 250)
    INTO facilities VALUES (2107, 2008, 9, 20, 800, 1, 300)
    INTO facilities VALUES (2108, 2008, 13, 19, 600, 0, 200)
    INTO facilities VALUES (2109, 2010, 10, 23, 400, 1, 100)
    INTO facilities VALUES (2110, 2011, 15, 23, 2000, 0, 800)
    INTO facilities VALUES (2111, 2012, 9, 18, 300, 0, 100)
    INTO facilities VALUES (2112, 2013, 10, 20, 500, 1, 150)
    INTO facilities VALUES (2113, 2014, 11, 22, 350, 0, 120)
    INTO facilities VALUES (2114, 2015, 19, 1, 800, 0, 250)
    INTO facilities VALUES (2115, 2015, 14, 23, 600, 0, 200)
    SELECT * FROM dual;
    
COMMIT;

-- Insert data into reviews table

INSERT ALL
    INTO reviews VALUES (3001, 2001, 1101, 4, 'Great venue, spacious and well-maintained.', TO_DATE('2023-08-01', 'yyyy-mm-dd'))
    INTO reviews VALUES (3002, 2001, 1105, 5, 'Had an amazing event at Venue A!', TO_DATE('2023-07-28', 'yyyy-mm-dd'))
    INTO reviews VALUES (3003, 2002, 1102, 5, 'The ballroom was stunning, perfect for our wedding.', TO_DATE('2023-06-15', 'yyyy-mm-dd'))
    INTO reviews VALUES (3004, 2004, 1106, 4, 'Garden Oasis provided a beautiful backdrop for our event.', TO_DATE('2023-08-02', 'yyyy-mm-dd'))
    INTO reviews VALUES (3005, 2006, 1103, 5, 'The Grand Hall is a historic gem, highly recommended.', TO_DATE('2023-07-20', 'yyyy-mm-dd'))
    INTO reviews VALUES (3006, 2006, 1107, 4, 'Impressed by the ambiance and service at The Grand Hall.', TO_DATE('2023-07-25', 'yyyy-mm-dd'))
    INTO reviews VALUES (3007, 2008, 1110, 4, 'Enjoyed our corporate retreat at Lakeside Retreat.', TO_DATE('2023-08-03', 'yyyy-mm-dd'))
    INTO reviews VALUES (3008, 2010, 1109, 5, 'Lovely outdoor event at Garden Terrace.', TO_DATE('2023-07-22', 'yyyy-mm-dd'))
    INTO reviews VALUES (3009, 2011, 1104, 5, 'Had a blast hosting our sports event at The Ballpark.', TO_DATE('2023-08-04', 'yyyy-mm-dd'))
    INTO reviews VALUES (3010, 2015, 1108, 4, 'Tropical Paradise provided a fun atmosphere for our themed party.', TO_DATE('2023-07-30', 'yyyy-mm-dd'))
    SELECT * FROM dual;
    
COMMIT;

-- Insert data into bookings table

INSERT ALL
    INTO bookings VALUES (5001, 1101, 'Confirmed', 4500.00, 'ABCD12345', 12)
    INTO bookings VALUES (5002, 1101, 'Pending', 0.00, 'EFGH67890', 27)
    INTO bookings VALUES (5003, 1102, 'Confirmed', 9000.00, 'IJKL23456', 0)
    INTO bookings VALUES (5004, 1102, 'Confirmed', 10000.00, 'MNOP34567', 16)
    INTO bookings VALUES (5005, 1103, 'Confirmed', 7200.00, 'QRST45678', NULL)
    INTO bookings VALUES (5006, 1103, 'Pending', 0.00, 'UVWX56789', NULL)
    INTO bookings VALUES (5007, 1104, 'Confirmed', 5500.00, 'YZAB67890', 31)
    INTO bookings VALUES (5008, 1104, 'Confirmed', 6000.00, 'CDEF78901', NULL)
    INTO bookings VALUES (5009, 1105, 'Confirmed', 6300.00, 'GHIJ89012', 35)
    INTO bookings VALUES (5010, 1105, 'Confirmed', 7000.00, 'KLMN90123', 18)
    INTO bookings VALUES (5011, 1106, 'Confirmed', 8100.00, 'OPQR01234',  3)
    INTO bookings VALUES (5012, 1106, 'Confirmed', 9000.00, 'STUV12345', 29)
    INTO bookings VALUES (5013, 1107, 'Confirmed', 5000.00, 'WXYZ23456', 0)
    INTO bookings VALUES (5014, 1108, 'Confirmed', 7000.00, 'ABCD34567', 0)
    INTO bookings VALUES (5015, 1109, 'Confirmed', 5850.00, 'EFGH45678', 12)
    INTO bookings VALUES (5016, 1110, 'Confirmed', 8500.00, 'IJKL56789', 36)
    SELECT * FROM dual;

COMMIT;

-- Insert data into schedules table

INSERT ALL
    INTO schedules VALUES (2001, 5001, TO_DATE('2023-08-10', 'yyyy-mm-dd'), 480, 720)
    INTO schedules VALUES (2002, 5002, TO_DATE('2023-08-15', 'yyyy-mm-dd'), 540, 900)
    INTO schedules VALUES (2003, 5003, TO_DATE('2023-08-20', 'yyyy-mm-dd'), 600, 840)
    INTO schedules VALUES (2004, 5004, TO_DATE('2023-08-25', 'yyyy-mm-dd'), 720, 960)
    INTO schedules VALUES (2005, 5005, TO_DATE('2023-09-01', 'yyyy-mm-dd'), 540, 780)
    INTO schedules VALUES (2006, 5006, TO_DATE('2023-09-05', 'yyyy-mm-dd'), 480, 720)
    INTO schedules VALUES (2007, 5007, TO_DATE('2023-09-10', 'yyyy-mm-dd'), 600, 840)
    INTO schedules VALUES (2008, 5008, TO_DATE('2023-09-15', 'yyyy-mm-dd'), 540, 780)
    INTO schedules VALUES (2009, 5009, TO_DATE('2023-09-20', 'yyyy-mm-dd'), 480, 720)
    INTO schedules VALUES (2010, 5010, TO_DATE('2023-09-25', 'yyyy-mm-dd'), 600, 840)
    INTO schedules VALUES (2011, 5011, TO_DATE('2023-10-01', 'yyyy-mm-dd'), 540, 780)
    INTO schedules VALUES (2012, 5012, TO_DATE('2023-10-05', 'yyyy-mm-dd'), 720, 960)
    INTO schedules VALUES (2013, 5013, TO_DATE('2023-10-10', 'yyyy-mm-dd'), 600, 840)
    INTO schedules VALUES (2014, 5014, TO_DATE('2023-10-15', 'yyyy-mm-dd'), 540, 780)
    INTO schedules VALUES (2015, 5015, TO_DATE('2023-10-20', 'yyyy-mm-dd'), 480, 720)
    INTO schedules VALUES (2001, 5016, TO_DATE('2023-10-25', 'yyyy-mm-dd'), 600, 840)
SELECT * FROM dual;

COMMIT;


--    DELETE FROM schedules;
--    DELETE FROM bookings;
--    DELETE FROM reviews;
--    DELETE FROM facilities;
--    DELETE FROM venues;
--    DELETE FROM owners;
--    DELETE FROM renters;
--    DELETE FROM contactInfo;


-- Create some VIEW for Business Reports

-- 1. Display the total number of venues in the database.
CREATE VIEW totalVenues AS
SELECT COUNT(*) AS totalVenues
FROM venues;

--SELECT * FROM totalVenues;


-- 2, Display the total number of bookings in the database for each venue.
CREATE VIEW totalBookings AS
SELECT v.venueName, COUNT(b.bookingID) AS totalBookings
FROM venues v JOIN schedules s ON v.venueID = s.venueID
JOIN bookings b ON s.bookingID = b.bookingID
GROUP BY v.venueName;

--SELECT * FROM totalBookings;



-- 3. Display the total number of payments in the database for each venue.
CREATE VIEW totalPayments AS
SELECT v.venueName, SUM(b.payment) AS totalPayments
FROM venues v JOIN schedules s ON v.venueID = s.venueID
JOIN bookings b ON s.bookingID = b.bookingID
GROUP BY v.venueName
ORDER BY totalPayments DESC;

--SELECT * FROM totalPayments;


-- 4. Display the total number of payments in the database for each renter.
CREATE VIEW totalPaymentsByRenter AS
SELECT r.renterID, c.contactFirstName || ' ' || c.contactLastName AS contactFullname, SUM(b.payment) AS totalPayments
FROM renters r JOIN contactInfo c ON r.contactID = c.contactID
JOIN bookings b ON r.renterID = b.renterID
GROUP BY r.renterID, c.contactFirstName, c.contactLastName
ORDER BY totalPayments DESC;

--SELECT * FROM totalPaymentsByRenter;


-- 5. Display the booking for each venue in the order of the booking date.
CREATE VIEW bookingsByDate AS
SELECT v.venueName, b.confirmationCode, b.status, b.payment, b.discountPercent, b.renterID, s.scheduleDate
FROM venues v JOIN schedules s ON v.venueID = s.venueID
JOIN bookings b ON s.bookingID = b.bookingID
ORDER BY v.venueName;

--SELECT * FROM bookingsByDate;


--DROP VIEW totalVenues;
--DROP VIEW totalBookings;
--DROP VIEW totalPayments;
--DROP VIEW totalPaymentsByRenter;
--DROP VIEW bookingsByDate;
